;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="_Nexus.Abilities.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="_Nexus.Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="_Nexus.Cooldown.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="_Nexus.Data.Damage",DevComment="")
+GameplayTagList=(Tag="_Nexus.Data.Heal",DevComment="")
+GameplayTagList=(Tag="_Nexus.Events.Abilities.Activate.Dash",DevComment="")
+GameplayTagList=(Tag="_Nexus.Events.Abilities.Activate.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="_Nexus.Events.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="_Nexus.Events.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="_Nexus.Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="_Nexus.Weapon.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="_Nexus.Weapon.Ranged.Staff",DevComment="")
+GameplayTagList=(Tag="GameplayCue._Nexus.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue._Nexus.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue._Nexus.Heal.Burst",DevComment="")

